image: lorisleiva/laravel-docker:latest

stages:
  - build
  - test

composer:
  stage: build
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
  artifacts:
    expire_in: 1 month
    paths:
      - vendor/
  cache:
    key: ${CI_COMMIT_REF_NAME}_composer
    paths:
      - vendor/

npm:
  stage: build # Same stage as `composer` so that they run in parallel.
  script:
    - npm install
    - npm run production
    - npm run dev
  artifacts:
    expire_in: 1 month
    paths:
      - node_modules/
      - public/css/
      - public/js/
  cache:
    key: ${CI_COMMIT_REF_NAME}_npm
    paths:
      - node_modules/


phpunit:
  stage: test
  script:
    # This is just composer, running again.
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    # Noooww, let's get php in here
    - wget -O /usr/bin/phpunit https://phar.phpunit.de/phpunit-8.phar && chmod +x /usr/bin/phpunit
    - phpunit --log-junit phpunit-report.xml
  artifacts:
    reports:
      junit: phpunit-report.xml
