name: PHPUnit

on:
  push:
    branches-ignore:
      - 'i18n'
  pull_request:
    branches-ignore:
      - 'i18n'

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ 8.0 ]
        dependency-version: [ prefer-stable ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, bcmath, ctype, fileinfo, json, openssl, pdo, tokenizer, xml, gd
          coverage: xdebug

      - name: Copy .env
        run: cp .env.example .env

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Execute tests (Unit and Feature tests) via Laravel internal test management and PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test

      - name: Run codacy-coverage-reporter
        if: github.repository == 'Traewelling/traewelling'
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: clover.xml
